ntrip_client:
  ros__parameters:
    host: 192.168.167.134
    port: 2101
    mountpoint: REACH

    ntrip_version: null

    authenticate: true
    username: reach
    password: emlidreach

    ssl: false
    cert: null
    key: null
    ca_cert: null

    rtcm_frame_id: odom

    nmea_max_length: 128
    nmea_min_length: 3

    rtcm_message_package: rtcm_msgs

    reconnect_attempt_max: 10
    reconnect_attempt_wait_seconds: 5
    rtcm_timeout_seconds: 4


